### ISSUE TITLE
bug: 3D Viewer Visual doesn’t correctly color by parameter

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-powerbi-visuals#7]
## Description

Related to [this thread](https://speckle.community/t/3d-viewer-visual-doesnt-color-by-parameter/3773) reported by [Mohamed_Manseur](https://speckle.community/u/Mohamed_Manseur).

3D Viewer Visual does not color objects by parameter values. This can be tested and confirmed using the files/commit below👇.

## Expected Behaviour

Correctly coloring by the parameter value.

## Streams/Commits Used

[https://speckle.xyz/streams/8ae610689c/commits/d633cd7548](https://speckle.xyz/streams/8ae610689c/commits/d633cd7548)

## Files Used

[[Hopital test.pbix](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/ba213fba-c506-434a-8060-ce9ec134bc02/Hopital_test.pbix)](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/ba213fba-c506-434a-8060-ce9ec134bc02/Hopital_test.pbix)

## Screenshots

![image](https://user-images.githubusercontent.com/51519350/196117141-4e1cee7b-e22c-47d2-b7b1-a6a983177549.png)

**Comment by AlanRynne** [comment]
Not really a bug but an "unexpected result" of the way our viewer currently works.

Deeply nested properties must preserve the nesting in the name so that the viewer can pick up on that.

So if you want to color something using the `name` of a `level` of a `room`. The column should be called `level.name`

Solution has already been posted in the thread.
